# exception handle
# try:
#     print(10/0)
    
# except Exception as e:
#     print("custom error:", e)
    
# print("we are learning exceptio hanldling in python")

# try:
#     print(0/0)
# except Exception as e:
#     print(e)
# finally:
#     print("done")
# print("hello world")


# def total(a,b):
#     if a==0:
#         raise Exception ("a is 0")
#     else:
#         return a+b
# try:
#     print(total(5,9))
# except Exception as e:
#     print(e)
    
# or
# def total(a,b):
#     if a==0:
#         raise Exception ("divisor can not be zero")
#     else:
#         return a+b
# a=int(input("enter the value of a:"))
# b=int(input("Enter the value of b:"))

# try:
#     print(total(a,b))
# except Exception as e:
#     print(e)

# def user_message(name):
#     print(f"Hello, {name}")

# user_message('Rahul')
# user_message('Raj')

# def user(name,age=0):
#     print(name)
#     print(age)

# user('Rahul' ,60)

# module
# import datetime
# today=datetime.date.today()
# print(today)





